// Step pulses for motion/stepper.py, generated by a state machine in the RP1's PIO block.
// The RP1 times every edge itself, so load on the CPU can neither shift nor shorten a pulse.
//
// Build on the Pi (needs libpio-dev):
//   gcc -O2 -shared -fPIC -I/usr/include/piolib -o libstepgen.so stepgen.c -lpio

#include <errno.h>
#include <piolib.h>

// the state machine runs at 1 MHz, so one cycle is one microsecond
#define CYCLE_HZ 1000000

// cycles a step takes on top of its low-time loop
#define STEP_CYCLES 12

// one generator per process, the robot has one drive
static PIO pio;
static int sm = -1;

static uint16_t instructions[7];
static const pio_program_t program = { .instructions = instructions, .length = 7, .origin = -1 };

// A block is one FIFO word: the low-time loop count in the upper half, steps - 1 in the
// lower. The state machine sends exactly that many steps, then pushes a word to its RX FIFO
// so the host knows the block has been played. In pioasm:
//
//   .side_set 1 opt
//   .wrap_target
//       pull block      side 0       ; wait for a block, STEP stays low
//       out x, 16                    ; x = steps - 1, OSR keeps the low-time count
//   step:
//       mov y, osr      side 1 [7]   ; STEP high for 10 cycles
//       nop                    [1]
//   low:
//       jmp y-- low     side 0       ; STEP low for y + 1 cycles
//       jmp x-- step
//       push noblock                 ; block done
//   .wrap
static void build_program(void)
{
    instructions[0] = pio_encode_pull(false, true) | pio_encode_sideset_opt(1, 0);
    instructions[1] = pio_encode_out(pio_x, 16);
    instructions[2] = pio_encode_mov(pio_y, pio_osr) | pio_encode_sideset_opt(1, 1) | pio_encode_delay(7);
    instructions[3] = pio_encode_nop() | pio_encode_delay(1);
    instructions[4] = pio_encode_jmp_y_dec(4) | pio_encode_sideset_opt(1, 0);
    instructions[5] = pio_encode_jmp_x_dec(2);
    instructions[6] = pio_encode_push(false, false);
}

// claims a state machine and hands it the pin, 0 or a negative errno
int stepgen_open(unsigned pin)
{
    pio = pio_open(0);
    if (PIO_IS_ERR(pio))
        return PIO_ERR_VAL(pio);

    sm = pio_claim_unused_sm(pio, false);
    if (sm < 0) {
        pio_close(pio);
        return -EBUSY;
    }

    build_program();
    uint offset = pio_add_program(pio, &program);
    if (offset == PIO_ORIGIN_INVALID) {
        pio_sm_unclaim(pio, sm);
        pio_close(pio);
        return -ENOSPC;
    }

    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);

    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset, offset + program.length - 1);
    sm_config_set_sideset(&c, 2, true, false);   // one pin plus the "opt" enable bit
    sm_config_set_sideset_pins(&c, pin);
    sm_config_set_clkdiv_int_frac(&c, clock_get_hz(clk_sys) / CYCLE_HZ, 0);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
    return 0;
}

// Queues `steps` pulses, period_us apart, as one block. The FIFO must have room: a put to a
// full FIFO makes piolib end the process
int stepgen_put(unsigned period_us, unsigned steps)
{
    if (period_us < STEP_CYCLES || period_us - STEP_CYCLES > 0xffff || steps < 1 || steps > 0x10000)
        return -EINVAL;

    pio_sm_put(pio, sm, (period_us - STEP_CYCLES) << 16 | (steps - 1));
    return 0;
}

// number of blocks played since the last call
int stepgen_done(void)
{
    int n = pio_sm_get_rx_fifo_level(pio, sm);
    for (int i = 0; i < n; i++)
        pio_sm_get(pio, sm);
    return n;
}

// stops the state machine, the pin is left low
void stepgen_close(void)
{
    pio_sm_set_enabled(pio, sm, false);
    pio_close(pio);
}
