// Step pulses for the robot's steppers, generated by state machines in the RP1's PIO block.
// The RP1 times every edge itself, so load on the CPU can neither shift nor shorten a pulse.
// One channel per stepper: the drive along the rope and the ring that turns the cameras.
//
// Build on the Pi (needs libpio-dev):
//   gcc -O2 -shared -fPIC -I/usr/include/piolib -o libstepgen.so stepgen.c -lpio -pthread

#include <errno.h>
#include <pthread.h>
#include <piolib.h>

// the state machines run at 1 MHz, so one cycle is one microsecond
#define CYCLE_HZ 1000000

// cycles a step takes on top of its low-time loop
#define STEP_CYCLES 12

// state machines the PIO block offers, one per stepper
#define MAX_CHANNELS 4

static PIO pio;
static int open_channels;
static uint program_offset;
static int sm_of[MAX_CHANNELS] = { -1, -1, -1, -1 };

// piolib talks to the RP1 through one file descriptor and is not thread safe. The drive is
// fed from its own thread while the turret moves from another, so every call is serialised
static pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER;

static uint16_t instructions[7];
static const pio_program_t program = { .instructions = instructions, .length = 7, .origin = -1 };

// A block is one FIFO word: the low-time loop count in the upper half, steps - 1 in the
// lower. The state machine sends exactly that many steps, then pushes a word to its RX FIFO
// so the host knows the block has been played. In pioasm:
//
//   .side_set 1 opt
//   .wrap_target
//       pull block      side 0       ; wait for a block, STEP stays low
//       out x, 16                    ; x = steps - 1, OSR keeps the low-time count
//   step:
//       mov y, osr      side 1 [7]   ; STEP high for 10 cycles
//       nop                    [1]
//   low:
//       jmp y-- low     side 0       ; STEP low for y + 1 cycles
//       jmp x-- step
//       push noblock                 ; block done
//   .wrap
static void build_program(void)
{
    instructions[0] = pio_encode_pull(false, true) | pio_encode_sideset_opt(1, 0);
    instructions[1] = pio_encode_out(pio_x, 16);
    instructions[2] = pio_encode_mov(pio_y, pio_osr) | pio_encode_sideset_opt(1, 1) | pio_encode_delay(7);
    instructions[3] = pio_encode_nop() | pio_encode_delay(1);
    instructions[4] = pio_encode_jmp_y_dec(4) | pio_encode_sideset_opt(1, 0);
    instructions[5] = pio_encode_jmp_x_dec(2);
    instructions[6] = pio_encode_push(false, false);
}

// the program is the same for every stepper, it is loaded once and shared
static int attach(unsigned pin, int sm)
{
    if (open_channels == 0) {
        build_program();
        program_offset = pio_add_program(pio, &program);
        if (program_offset == PIO_ORIGIN_INVALID)
            return -ENOSPC;
    }

    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);

    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, program_offset, program_offset + program.length - 1);
    sm_config_set_sideset(&c, 2, true, false);   // one pin plus the "opt" enable bit
    sm_config_set_sideset_pins(&c, pin);
    sm_config_set_clkdiv_int_frac(&c, clock_get_hz(clk_sys) / CYCLE_HZ, 0);
    pio_sm_init(pio, sm, program_offset, &c);
    pio_sm_set_enabled(pio, sm, true);
    return 0;
}

// claims a state machine and hands it the pin, the channel number or a negative errno
int stepgen_open(unsigned pin)
{
    pthread_mutex_lock(&lock);

    int err = 0;
    int channel = -1;

    if (open_channels == 0) {
        pio = pio_open(0);
        if (PIO_IS_ERR(pio)) {
            err = PIO_ERR_VAL(pio);
            goto out;
        }
    }

    for (int i = 0; i < MAX_CHANNELS; i++) {
        if (sm_of[i] < 0) {
            channel = i;
            break;
        }
    }
    if (channel < 0) {
        err = -EBUSY;
        goto close_pio;
    }

    int sm = pio_claim_unused_sm(pio, false);
    if (sm < 0) {
        err = -EBUSY;
        goto close_pio;
    }

    err = attach(pin, sm);
    if (err < 0) {
        pio_sm_unclaim(pio, sm);
        goto close_pio;
    }

    sm_of[channel] = sm;
    open_channels++;
    pthread_mutex_unlock(&lock);
    return channel;

close_pio:
    if (open_channels == 0)
        pio_close(pio);
out:
    pthread_mutex_unlock(&lock);
    return err;
}

// Queues `steps` pulses, period_us apart, as one block. The FIFO must have room: a put to a
// full FIFO makes piolib end the process
int stepgen_put(int channel, unsigned period_us, unsigned steps)
{
    if (channel < 0 || channel >= MAX_CHANNELS || sm_of[channel] < 0)
        return -EINVAL;
    if (period_us < STEP_CYCLES || period_us - STEP_CYCLES > 0xffff || steps < 1 || steps > 0x10000)
        return -EINVAL;

    pthread_mutex_lock(&lock);
    pio_sm_put(pio, sm_of[channel], (period_us - STEP_CYCLES) << 16 | (steps - 1));
    pthread_mutex_unlock(&lock);
    return 0;
}

// number of blocks played since the last call
int stepgen_done(int channel)
{
    if (channel < 0 || channel >= MAX_CHANNELS || sm_of[channel] < 0)
        return -EINVAL;

    pthread_mutex_lock(&lock);
    int n = pio_sm_get_rx_fifo_level(pio, sm_of[channel]);
    for (int i = 0; i < n; i++)
        pio_sm_get(pio, sm_of[channel]);
    pthread_mutex_unlock(&lock);
    return n;
}

// stops the state machine, the pin is left low. The PIO itself is released with the last channel
void stepgen_close(int channel)
{
    if (channel < 0 || channel >= MAX_CHANNELS || sm_of[channel] < 0)
        return;

    pthread_mutex_lock(&lock);
    pio_sm_set_enabled(pio, sm_of[channel], false);
    pio_sm_unclaim(pio, sm_of[channel]);
    sm_of[channel] = -1;

    if (--open_channels == 0)
        pio_close(pio);
    pthread_mutex_unlock(&lock);
}
